import { Meetup } from './meetup.model';

export const MEETUPS: Meetup[] = [
 new Meetup("http://www.mybulkleylakesnow.com/wp-content/uploads/2015/11/books-stock.jpg", "First Thursday Book Club",
     "Thursday, February 2, 2017", "6:00 PM to 8:00 PM", "Studio Nia", "918 SW Yamhill Street, 4th Floor, Portland, OR ", "Joseph Wachunas will resume meetings of the First Thursday Book Club (FTBC) in February. This particular meetup is best suited for adults with an Intermediate to advanced level knowledge of the Italian language. Please join Joe in reading La testa degli Italiani by Beppe Severgnini. It is recommended that participants have both versions of the text, Italian and English. The English version is titled La Bella Figura. A free pdf version in Italian is available.", "https://www.meetup.com/Italian-Language-Culture-Connect-OR/events/236608239/"),
 new Meetup("http://www.mybulkleylakesnow.com/wp-content/uploads/2015/11/books-stock.jpg", "First Thursday Book Club",
     "Thursday, February 2, 2017", "6:00 PM to 8:00 PM", "Studio Nia", "918 SW Yamhill Street, 4th Floor, Portland, OR ", "Joseph Wachunas will resume meetings of the First Thursday Book Club (FTBC) in February. This particular meetup is best suited for adults with an Intermediate to advanced level knowledge of the Italian language. Please join Joe in reading La testa degli Italiani by Beppe Severgnini. It is recommended that participants have both versions of the text, Italian and English. The English version is titled La Bella Figura. A free pdf version in Italian is available.", "https://www.meetup.com/Italian-Language-Culture-Connect-OR/events/236608239/"),
 new Meetup("http://www.mybulkleylakesnow.com/wp-content/uploads/2015/11/books-stock.jpg", "First Thursday Book Club",
     "Thursday, February 2, 2017", "6:00 PM to 8:00 PM", "Studio Nia", "918 SW Yamhill Street, 4th Floor, Portland, OR ", "Joseph Wachunas will resume meetings of the First Thursday Book Club (FTBC) in February. This particular meetup is best suited for adults with an Intermediate to advanced level knowledge of the Italian language. Please join Joe in reading La testa degli Italiani by Beppe Severgnini. It is recommended that participants have both versions of the text, Italian and English. The English version is titled La Bella Figura. A free pdf version in Italian is available.", "https://www.meetup.com/Italian-Language-Culture-Connect-OR/events/236608239/")

];
